

SET TRANSACTION NAME 'ADDING_CREATED_DATE_ATTRIBUTE';

    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(4,'CREATED');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(5, 1);

COMMIT;


--CREATE TTT GAME
SET TRANSACTION NAME 'CREATING_TTT_OBJECT_TYPE';
    --TICTACTOE ES 5
    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('TICTACTOE', 1, 0);
    --CREAR LOS ATRIBUTOS PARA PERSONA
    /*INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES (2, 'ID');

    --ASIGNAR EL ATRIBUTO
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(9, 6);
*/

    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 5);    
COMMIT;

-- CREATE TURN
SET TRANSACTION NAME 'CREATING_TURN_OBJECT_TYPE';
    --TURN ES 6
    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('TURN', 1, 0);
    --BOOLEAN-NUMERIC
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(3, 'ISFINISHED');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PLAYER1');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PLAYER2');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'WINNER');

    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 6);    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(10, 6);    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(11, 6);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(12, 6);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(13, 6);
    
COMMIT;

SET TRANSACTION NAME 'CREATING_SQUARE_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('SQUARE', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(2, 'ROW');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(2, 'COLUMN');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PIECE');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 7);    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(14, 7);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(15, 7);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(16, 7);

COMMIT;

SET TRANSACTION NAME 'CREATING_PLAYER_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('PLAYER', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(0, 'TYPE');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 8);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(2, 8);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(17, 8);

COMMIT;