
SET TRANSACTION NAME 'NEW_FIVETH_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'MY FIVETH PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 44, '44');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 44, 'JOSELYN');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 44, 'HUMAN');    

COMMIT;

SET TRANSACTION NAME 'NEW_SIXTH_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'MY SIXTH PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 45, '45');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 45, 'MARIO');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 45, 'BOT');    

COMMIT;

SET TRANSACTION NAME 'NEW_SEVENTH_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'MY SEVENTH PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 46, '46');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 46, 'DANIEL');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 46, 'HUMAN');    

COMMIT;

SET TRANSACTION NAME 'NEW_EIGHTH_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'MY EIGHTH PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 47, '47');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 47, 'MARIANA');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 47, 'BOT');    

COMMIT;
/*
SET TRANSACTION NAME 'NEW_NINTH_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'MY NINTH PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 48, '48');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 48, 'CARLA');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 48, 'HUMAN');    

COMMIT;

SET TRANSACTION NAME 'NEW_TENTH_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'MY TENTH PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 49, '49');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 49, 'FRANCISCO');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 49, 'BOT');    

COMMIT;*/