--CREACION DE OBJETOS

SET TRANSACTION NAME 'CREATING_TTT_OBJECT_TYPE';
    --TICTACTOE ES 5
    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('TICTACTOE', 1, 0);
    --ASIGNAR EL ATRIBUTO
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(3, 6);

COMMIT;

SET TRANSACTION NAME 'CREATING_TURN_OBJECT_TYPE';
    --TURN ES 7
    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('TURN', 1, 0);
    --BOOLEAN-NUMERIC
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(3, 'ISFINISHED');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PLAYER1');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PLAYER2');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'WINNER');

    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 7);    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(6, 7);    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(7, 7);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(8, 7);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(9, 7);
    
COMMIT;

SET TRANSACTION NAME 'CREATING_SQUARE_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('SQUARE', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(2, 'ROW');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(2, 'COLUMN');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PIECE');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 8);    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(10, 8);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(11, 8);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(12, 8);

COMMIT;

SET TRANSACTION NAME 'CREATING_PLAYER_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('PLAYER', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(0, 'TYPE');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 9);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(2, 9);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(13, 9);

COMMIT;

SET TRANSACTION NAME 'CREATING_PLAYER_TURN_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('PLAYER_TURN', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PLAYER');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PIECE');

    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 10);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(14, 10);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(15, 10);

COMMIT;


SET TRANSACTION NAME 'CREATING_PLIECE_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('PIECE', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(0, 'PIECE');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 11);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(16, 11);

COMMIT;


---INSTANCIAS
SET TRANSACTION NAME 'NEW_TICTACTOE_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(6, 'TICTACTOE');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 1, '1');

COMMIT;

SET TRANSACTION NAME 'NEW_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'MY FIRST PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 2, '2');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 2, 'PEDRO');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 2, 'HUMAN');    

COMMIT;

SET TRANSACTION NAME 'NEW_SECOND_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'MY SECOND PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 3, '3');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 3, 'CARLOS');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 3, 'HUMAN');    

COMMIT;

SET TRANSACTION NAME 'NEW_THIRD_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'MY THIRD PLAYER');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 4, '4');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 4, 'MARCOS');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 4, 'BOT');    

COMMIT;

SET TRANSACTION NAME 'NEW_FOURTH_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'MY FOURTH PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 5, '5');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 5, 'ALEJANDRA');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 5, 'HUMAN');    

COMMIT;

SET TRANSACTION NAME 'NEW_PIECE_X_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(11, 'PIECE X');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 6, '6');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(16, 6, 'X');

COMMIT;

SET TRANSACTION NAME 'NEW_PIECE_O_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(11, 'PIECE O');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 7, '7');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(16, 7, 'O');

COMMIT;