/*Jugadores que han ganado al menos una partida*/

CREATE VIEW WINNERS_PARAMS
AS (SELECT ATTR_ID,  OBJECT_ID, VALUE FROM  DSU_PARAMS
WHERE ATTR_ID = 9);

CREATE VIEW WINNER_PLAYERS
AS (
SELECT INF_WINNERS.OBJECT_ID, PAR_WINNERS.VALUE AS NAME FROM
    (
        SELECT WINNERS_ID.OBJECT_ID, WINNERS_ID.NAME FROM
            (
                SELECT  WINN_PAR_OBJ.OBJECT_ID, WINN_PAR_OBJ.NAME, PAR2.VALUE FROM
                    (
                        SELECT OBJ.OBJECT_ID,  OBJ.NAME FROM
                            (
                                SELECT * FROM WINNERS_PARAMS
                            ) WINN_PAR 

                            JOIN DSU_OBJECTS OBJ ON WINN_PAR.VALUE = OBJ.OBJECT_ID
                    )WINN_PAR_OBJ 

                    JOIN DSU_PARAMS PAR2 ON WINN_PAR_OBJ.OBJECT_ID = PAR2.OBJECT_ID
                    AND PAR2.ATTR_ID = 14
            ) WINNERS_VALUE 

            JOIN DSU_OBJECTS WINNERS_ID ON WINNERS_VALUE.VALUE = WINNERS_ID.OBJECT_ID
    ) INF_WINNERS 

    JOIN DSU_PARAMS PAR_WINNERS ON INF_WINNERS.OBJECT_ID = PAR_WINNERS.OBJECT_ID
    AND ATTR_ID = 2;
)

/*Jugadores que han perdido al menos una partida*/
--PLAYER PER EACH TURN
SELECT ID_PLAYERS_IN_TURNS.NAME, ID_PLAYERS_IN_TURNS.VALUE AS ID_PLAYER FROM
        (
            SELECT * FROM WINNER_PLAYERS
        ) OBJECTS_NAMES
RIGHT JOIN 
    (
    SELECT PLAYERS_IN_TURNS.OBJECT_ID, PLAYERS_IN_TURNS.NAME, PAR6.ATTR_ID, PAR6.VALUE FROM
        (
            SELECT  TURNS.OBJECT_ID, TURNS.NAME, PAR5.VALUE FROM 
            
                (
                    SELECT * FROM TURNS_OBJ 
                ) TURNS
                
                JOIN DSU_PARAMS PAR5 ON  TURNS.OBJECT_ID = PAR5.OBJECT_ID
                WHERE PAR5.ATTR_ID = 7  OR  PAR5.ATTR_ID = 8
        ) PLAYERS_IN_TURNS
        
        JOIN  DSU_PARAMS PAR6 ON  PLAYERS_IN_TURNS.VALUE = PAR6.OBJECT_ID 
        WHERE PAR6.ATTR_ID = 14 /*ID_PLAYER*/
    ) ID_PLAYERS_IN_TURNS
    
ON OBJECTS_NAMES.OBJECT_ID = ID_PLAYERS_IN_TURNS.VALUE ORDER BY NAME ASC;


/*Jugadores que no han jugado una partida*/
--I HAVE ID OF PLAYERS WITH AT LEAST A TURN



/*Como quedó el tablero del mejor jugador*/



/*Como quedó el tablero del peor jugador*/


/*Parametros de un objeto*/
SELECT RES1.NAME, RES1.DATE_VALUE, RES1.ATTRIBUTE, RES1.VALUE, TYP.NAME AS TYPE
FROM
    (
        SELECT RES.NAME, RES.DATE_VALUE, ATT.NAME 
        AS ATTRIBUTE, RES.VALUE, ATT.ATTR_TYPE_ID
        FROM
        (
            SELECT OBJ.NAME, PAR.VALUE, PAR.LIST_VALUE_ID,  PAR.DATE_VALUE, PAR.ATTR_ID
            FROM  DSU_OBJECTS OBJ 
            JOIN DSU_PARAMS PAR
            ON OBJ.OBJECT_ID = PAR.OBJECT_ID
            AND  OBJ.OBJECT_ID = 2
        ) RES 
            JOIN DSU_ATTRIBUTES ATT
            ON RES.ATTR_ID = ATT.ATTR_ID
        ) RES1 
            JOIN DSU_ATTRIBUTES_TYPES TYP
            ON RES1.ATTR_TYPE_ID = TYP.ATTR_TYPE_ID;
