SET TRANSACTION NAME 'THIRD_TURN';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(10, 'FIVETH PLAYER');

    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 32, '32');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(14, 32, '4');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 32, '6');


    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(10, 'SIXTH PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 33, '33');   
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(14, 33, '5');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 33, '7');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(7, 'THIRD TURN');

    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 34, '34'); 
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(6, 34, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(7, 34, '20');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(8, 34, '21');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(9, 34, '21');


    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 1,1');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 35, '35');  
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 35, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 35, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 35, '6');

    
    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 1,2');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 36, '36');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 36, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 36, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 36, '6');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 1,3');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 37, '37');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 37, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 37, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 37, '7');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 2,1');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 38, '38');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 38, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 38, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 38, '6');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 2,2');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 39, '39');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 39, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 39, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 39, '7');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 2,3');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 40, '40');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 40, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 40, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 40, '7');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 3,1');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 41, '41');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 41, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 41, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 41, '6');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 3,2');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 42, '42');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 42, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 42, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 42, '7');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 3,3');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 43, '43');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 43, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 43, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 43, '6');
    
    --REFERENCE TO THIRD__TURN IN DSU_OBJECT_TYPES
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(1, 34);
    
    --REFERENCE EACH POSITION TO PLAYER_TURN 34
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(34, 35);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(34, 36);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(34, 37);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(34, 38);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(34, 39);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(34, 40);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(34, 41);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(34, 42);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(34, 43);

COMMIT;