SET TRANSACTION NAME 'FIRST_TURN';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(10, 'FIRST PLAYER');

    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 8, '8'); 
    --PLAYER DEL OBJETO 8 TIENE UN VALOR DE 2 = first player
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(14, 8, '2');
    --PIECE DEL OBJETO 8 TENDRA UN VALOR DE 7
    --7 O
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 8, '7');

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(10, 'SECOND PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 9, '9');   
    --PLAYER DEL OBJETO 9 TIENE UN VALOR DE 2 = second player
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(14, 9, '3');
    --6 X
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 9, '6');
    

    /*CREATING_TURN_OBJECT_TYPE*/
    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(7, 'FIRST TURN');

    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 10, '10'); 
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(6, 10, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(7, 10, '8');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(8, 10, '8');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(9, 10, '9');
    
    --SQUARES-POSSITIONS
    
    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 1,1');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 11, '11');  
    --ROW  
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 11, '1');
    --COLUMN
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 11, '1');
    --PIECE
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 11, '7');

    
    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 1,2');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 12, '12');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 12, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 12, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 12, '7');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 1,3');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 13, '13');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 13, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 13, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 13, '7');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 2,1');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 14, '14');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 14, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 14, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 14, '6');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 2,2');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 15, '15');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 15, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 15, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 15, '6');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 2,3');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 16, '16');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 16, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 16, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 16, '6');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 3,1');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 17, '17');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 17, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 17, '1');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 17, '7');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 3,2');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 18, '18');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 18, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 18, '2');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 18, '6');
    

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(8, 'SQUARE 3,3');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 19, '19');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(10, 19, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(11, 19, '3');
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(15, 19, '6');
    
    --REFERENCE TO PLAYER_TURN IN DSU_OBJECT_TYPES
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(1, 10);
    
    --REFERENCE EACH POSITION TO PLAYER_TURN 10
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(10, 11);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(10, 12);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(10, 13);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(10, 14);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(10, 15);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(10, 16);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(10, 17);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(10, 18);
    INSERT INTO DSU_REFERENCE(OBJECT_ID, REFERENCE) VALUES(10, 19);

COMMIT;