--INITIAL DATA PREVIOUS PROJECT

--CREATING_TYPES
SET TRANSACTION NAME 'CREATING_TYPES';
    INSERT INTO DSU_OBJECT_TYPES(NAME, ISABSTRACT) VALUES ('ALL', 0);
commit;


SET TRANSACTION NAME 'CREATING_PERSON_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT)  VALUES ('PERSON', 1, 0);

    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES (2, 'ID');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES (0, 'NAME');

    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (1,2);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (2,2);

COMMIT;


SET TRANSACTION NAME 'CREATING_DEVICE_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES ('DEVICE', 1, 0);
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES (9, 'OWNER');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (1,3);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (2,3);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (3,3);

COMMIT;


SET TRANSACTION NAME 'CREATING_ROUTER_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES ('ROUTER', 3, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES (0, 'MANUFACTURE');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (4,4);

COMMIT;

SET TRANSACTION NAME 'CREATING_SWITCH_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES ('SWITCH', 3, 0);
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (4,5);

COMMIT;

SET TRANSACTION NAME 'ADDING_CREATED_DATE_ATTRIBUTE';

    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(4,'CREATED');
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(5, 1);

COMMIT;